# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.runs/synth_1/design_1_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.collectionResultDisplayLimit 0
set_param power.BramSDPPropagationFix 1
set_param chipscope.maxJobs 5
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL-1065} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.cache/wt [current_project]
set_property parent.project_path E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu104:part0:1.1 [current_project]
set_property ip_repo_paths {
  e:/im_always_learning/E906_zcu/EGRET_cfg
  e:/im_always_learning/E906_zcu/opene906-main/E906_RTL_FACTORY/gen_rtl
} [current_project]
update_ip_catalog
set_property ip_output_repo e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/sources_1/imports/include/tdt_dmi_define.h
  E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/sources_1/imports/include/tdt_define.h
  E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/sources_1/imports/include/sysmap.h
  E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/sources_1/imports/include/pa_idu_cfig.h
  E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/sources_1/imports/include/pa_dtu_cfig.h
  E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/sources_1/imports/include/cpu_cfig.h
}
set_property file_type "Verilog Header" [get_files E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/sources_1/imports/include/tdt_dmi_define.h]
set_property is_global_include true [get_files E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/sources_1/imports/include/tdt_dmi_define.h]
set_property file_type "Verilog Header" [get_files E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/sources_1/imports/include/tdt_define.h]
set_property is_global_include true [get_files E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/sources_1/imports/include/tdt_define.h]
set_property file_type "Verilog Header" [get_files E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/sources_1/imports/include/sysmap.h]
set_property is_global_include true [get_files E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/sources_1/imports/include/sysmap.h]
set_property file_type "Verilog Header" [get_files E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/sources_1/imports/include/pa_idu_cfig.h]
set_property is_global_include true [get_files E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/sources_1/imports/include/pa_idu_cfig.h]
set_property file_type "Verilog Header" [get_files E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/sources_1/imports/include/pa_dtu_cfig.h]
set_property is_global_include true [get_files E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/sources_1/imports/include/pa_dtu_cfig.h]
set_property file_type "Verilog Header" [get_files E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/sources_1/imports/include/cpu_cfig.h]
set_property is_global_include true [get_files E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/sources_1/imports/include/cpu_cfig.h]
read_verilog -library xil_defaultlib E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_ahblite_axi_bridge_0_0/design_1_ahblite_axi_bridge_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_ahblite_axi_bridge_1_0/design_1_ahblite_axi_bridge_1_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/bd_f60c_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/bd_f60c_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.gen/sources_1/bd/design_1/design_1_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/constrs_1/new/1.xdc
set_property used_in_implementation false [get_files E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/constrs_1/new/1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental E:/im_always_learning/E906_zcu/vivado_e906_zcu/vivado_e906_zcu.srcs/utils_1/imports/synth_1/design_1_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top design_1_wrapper -part xczu7ev-ffvc1156-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
